version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_c3
    environment:
      SA_PASSWORD: "Password123#"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - appnet
    healthcheck:
      test: ["CMD-SHELL", "timeout 1 bash -c '</dev/tcp/localhost/1433'"]
      interval: 10s
      retries: 5
      start_period: 30s

  app:
    build:
      context: ./AuthenticationService
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - "5540:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - appnet

networks:
  appnet:
